### ISSUE TITLE
CECON keyword not recognised by OPM (parser)

### ISSUE THREAD

**Issue by igorbagno** [OPM/opm-parser#1047]
Hello,  

I am currently working on a simulation case study requiring the modelling of water shut-off type of well interventions. I've tried to implement the CECON optionality to shut the most offending connections in terms of WCT. It appears that Flow (parser) doesn't recognise the CECON keyword.  

Please, let me know if it is in the plans for further development and/or if any alternative optionality to model the water shut-off in a well exists in Flow.  

Thanks in advance!  

Regards, 
Igor Bagno

**Comment by andlaus** [comment]
that's strange: the parser should accept this keyword since Dec 14, 2016:

https://github.com/OPM/opm-parser/blob/master/opm/parser/share/keywords/000_Eclipse100/C/CECON

maybe you haven't updated in a while? also, if the problem is from within ResInsight, it's probably because their fork of opm-parser has not been updated for a while. (as far as I can see since mid-october 2016.) I guess this demonstrates the drawbacks of bundling a fork of everything with a project. ;)

support for CECON in the simulator is not there yet as far as I know, and would require large amounts of work.

**Comment by OPMUSER** [comment]
About using WECON instead, is that available in FLOW?
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by igorbagno** [comment]
David,

thanks for your reply. Testing WECON now. But eventually WECON would have some limitations in comparison with CECON.

Igor

**Comment by igorbagno** [comment]
Andlaus, 

What do you mean that CECON should be accepted by parser but not supported in the simulator?

Thanks!

Igor

**Comment by joakim-hove** [comment]
> What do you mean that CECON should be accepted by parser but not supported in the simulator?

That means that the program `flow_xxx` will read and internalize the `CECON` keyword, including to handle defaults and do some basic error checking. But when `flow_xxx` actually starts simulating it will *completely ignore* the behavior requested through the use of the `CECON` keyword. As @andlaus says I think fully supporting the `CECON` keyword will be a large undertaking - not something which is planned for now.

**Comment by igorbagno** [comment]
Thanks, Joakim

**Comment by igorbagno** [comment]
David, 

WECON works fine when shutting the most offending connection. Thank you for your comment.

Regards,

Igor

**Comment by igorbagno** [comment]
Andlaus, Joakim,

last question on whether COMPLUMP keyword is supported? And if not what are the plans for its implementation?

I made few test runs with WECON which works fine, also included COMPLUMP to lump the connections and model the workovers by completion (group of connections). COMPLUMP seems to be recognised by the parser, however, there was no change in the response between the runs with and without COMPLUMP, i.e. the connections were shut one by one and not by completion.

Thanks again,

Igor

**Comment by OPMUSER** [comment]
Igor,

Same as CECON, COMPLUMP recognized by the parser but not implemented in 
FLOW.

I know because I had the same problem a few months back that caused the 
parser to throw an exception. So they  implemented the keyword but not 
the feature associated with the keyword, just the first step of many to 
get all this working

If it is water you are try to control use the +CON option on WECON 
keyword that will shut the worst offending completion and all those 
below it. Not perfect I know.
ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by igorbagno** [comment]
Ok, thanks, David, that's what I understood and yes, the +CON in WECON can be some sort of temporary solution. I find this optionality quite useful and important to implement in Flow, especially for the optimisation type of projects.

Thanks again!

Regards,

Igor

**Comment by andlaus** [comment]
As I see it, we intend to implement full support for these keywords eventually. It currently is just not a high priority, but this can change depending of the objectives which we get...

**Comment by igorbagno** [comment]
Ok, thanks, Andlaus, I'll keep checking for the updates on that in future releases.

Regards,

Igor
