### ISSUE TITLE
About the handling of defaulted value

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-parser#626]
For one keyword, the defaulted value is something like 0.0. 
That means, if we do not specify the value, it will be 0.0.  
And also, if the value is defaulted, some other procedure will be performed to get the actually useful value (usually not 0.0). 

The question is, will Eclipse handle it differently if we leave the keyword defaulted or specify a defaulted value (0.0 here) there?

**Comment by joakim-hove** [comment]
The question of defaults has been a long and winding road. The current best practice which I try to enforce is:

1. Be very cautious of dummy values like -1. The general principle is that a value which is stored in the Json configuration should be valid for immediate use. 

2. You have *three*  related methods to choose from:

    **hasValue( ):** This will check if the item has a value, it will not differentiate between default values and values entered from the deck. In the case of items which have a default specified in the Json configuration this method does not make much sense - it will *always* return true.

    **defaultApplied():** This will check if the default mechanism has been used for the current item.

    **getValue():** Will return the current value - will *not* differentiate between values entered in the deck and default values fetched from the Json configuration.

     Make sure to understand the difference between the three - and use the right method(s). If the default value in the Json is perfectly legitimate and ready to use - just go ahead with **getValue( )**. Otherwise I feel the cleanest is to branch on **defaultApplied( )**.

> And also, if the value is defaulted, some other procedure will be performed to get the actually useful value (usually not 0.0).

Yes - and in that situation I really think using **defaultAplied()** to check is preferable.

>The question is, will Eclipse handle it differently if we leave the keyword defaulted or specify a defaulted value (0.0 here) there?

Well - that is the million-dollar question - the honest answer is "I don't know"; my hunch is that the correct answer is "it depends". The method which is currently missing is something like **hasDefaultValue( )** - which would return true if the current value entered explicitly in the input deck corresponds to the default value found in the Json. Do you need such functionality now? I would much prefer that this was a method on the `DeckItem` class, rather than people doing
```C++
if (item->getValue(0) == -1)
   // Default path
else
   // Explicit input path
```

in the consumer code.

**Comment by GitPaean** [comment]
Thanks for the responses. It is very helpful. There are some default values not ready for immediate use. They are used for indicating future processing to obtain the value.
