### ISSUE TITLE
PORV=0 and ACTNUM

### ISSUE THREAD

**Issue by totto82** [OPM/opm-parser#802]
I am running the BRUGGE case. In this case there are many cells with zero porosity, but ACTNUM is not used to make this cells inactive. Cells with PORV=0 should be treated automaticly as non-active cells by the simulator. I have a fix for this in opm-core in the grid-processing, still I add this as an issue to opm-parser as I think this behaviour belongs in the parser.

**Comment by pgdr** [comment]
This might be handled by a one-liner in [EclipseState.cpp#L66](https://github.com/pgdr/opm-parser/blob/master/opm/parser/eclipse/EclipseState/EclipseState.cpp#L66).

**Comment by pgdr** [comment]
Do you have test data?  Here's a naïve patch (prototype) that I can test if you have some data I can test on.

By the way, should the converse also be done; if `actnum` is 0, set `poro` and `ntg` to 0?

    diff --git a/opm/parser/eclipse/EclipseState/EclipseState.cpp b/opm/parser/eclipse/EclipseState/EclipseState.cpp
    index bd5071e..fa52bed 100644
    --- a/opm/parser/eclipse/EclipseState/EclipseState.cpp
    +++ b/opm/parser/eclipse/EclipseState/EclipseState.cpp
    @@ -80,8 +80,17 @@ namespace Opm {
    
             // after Eclipse3DProperties has been constructed, we have complete ACTNUM info
    -        if (m_eclipseProperties.hasDeckIntGridProperty("ACTNUM"))
    -            m_inputGrid->resetACTNUM(m_eclipseProperties.getIntGridProperty("ACTNUM").getData().data());
    +        if (m_eclipseProperties.hasDeckIntGridProperty("ACTNUM")) {
    +            std::vector<int> actnum  = m_eclipseProperties.getIntGridProperty("ACTNUM").getData();
    +            std::vector<double> poro = m_eclipseProperties.getDoubleGridProperty("PORO").getData();
    +            std::vector<double> ntg  = m_eclipseProperties.getDoubleGridProperty("NTG").getData();
    +            size_t m = std::min(ntg.size(), poro.size());
    +            for (size_t i = 0; i < m; i++) {
    +                if (ntg[i] == 0 || poro[i] == 0)
    +                    actnum[i] = 0;
    +            }
    +            m_inputGrid->resetACTNUM(actnum.data());
    +        }

**Comment by OPMUSER** [comment]
The correct logic is that if the PV is zero the block is inactive

PV = ACTNUM*PORO*NTG*H

In fact in ECLIPSE if you accidentally set ACTNUM to 2 by mistake, then the PV doubles.


David Baxendale
Senior Petroleum Engineering Advisor
RPS Energy
8 Temasek Boulevard,
23-05 Suntec Tower 3
Singapore, 038988

Dir:
Tel:
Fax:
Mobile:
Email:
www:

+65 6499 0063
+65 6499 0060
+65 6499 0069
+65 9173 7031
david.baxendale@rpsgroup.com.sg<mailto:david.baxendale@rpsgroup.com.sg>
http://www.rpsgroup.com<http://www.rpsgroup.com/>

Please note change of address

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.

Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by any other means.




On 11-May-16 15:53, Pål Grønås Drange wrote:

Do you have test data? Here's a naïve patch (prototype) that I can test if you have some data I can test on.

By the way, should the converse also be done; if actnum is 0, set poro and ntg to 0?

diff --git a/opm/parser/eclipse/EclipseState/EclipseState.cpp b/opm/parser/eclipse/EclipseState/EclipseState.cpp
index bd5071e..fa52bed 100644
--- a/opm/parser/eclipse/EclipseState/EclipseState.cpp
+++ b/opm/parser/eclipse/EclipseState/EclipseState.cpp
@@ -80,8 +80,17 @@ namespace Opm {

         // after Eclipse3DProperties has been constructed, we have complete ACTNUM info
-        if (m_eclipseProperties.hasDeckIntGridProperty("ACTNUM"))
-            m_inputGrid->resetACTNUM(m_eclipseProperties.getIntGridProperty("ACTNUM").getData().data());
+        if (m_eclipseProperties.hasDeckIntGridProperty("ACTNUM")) {
+            std::vector<int> actnum  = m_eclipseProperties.getIntGridProperty("ACTNUM").getData();
+            std::vector<double> poro = m_eclipseProperties.getDoubleGridProperty("PORO").getData();
+            std::vector<double> ntg  = m_eclipseProperties.getDoubleGridProperty("NTG").getData();
+            size_t m = std::min(ntg.size(), poro.size());
+            for (size_t i = 0; i < m; i++) {
+                if (ntg[i] == 0 || poro[i] == 0)
+                    actnum[i] = 0;
+            }
+            m_inputGrid->resetACTNUM(actnum.data());
+        }

**Comment by atgeirr** [comment]
> In fact in ECLIPSE if you accidentally set ACTNUM to 2 by mistake, then the PV doubles.

That is quite funny! Apart from the fact that someone probably uses this to hack the pore volumes...

**Comment by pgdr** [comment]
My very limited experience with ECLIPSE aside ... it seems there is a fine line between funny and scary.

**Comment by joakim-hove** [comment]
>@totto82: I have a fix for this in opm-core in the grid-processing, still I add this as an issue to opm-parser as I think this behaviour belongs in the parser.

Well - as you correctly indicate this should be fixed in the parser; so why do you do it in opm-core? We should strive harder to fix the problems properly - and avoid band-aid solutions.

As indicated py @pgdr it is really a quite simple fix. Instead of using the `PORO` and `NTG`directly, I would rather recommend using the `PORV` GridProperty - where the `PORO` and `NTG`multiplication has already been performed: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/EclipseState.cpp#L83

```C++
{
    // Not necessary to check if they are in the deck - will be autocreated.
    std::vector<int> actnum  = m_eclipseProperties.getIntGridProperty("ACTNUM").getData();
    std::vector<double> porv = m_eclipseProperties.getDoubleGridProperty("PORV").getData();

    for (size_t i = 0; i < porv.size(); i++) {
         if (porv[i] == 0)  
            actnum[i] = 0;
    }
     
    m_inputGrid->resetACTNUM(actnum.data()); 
}
```

> @pgdr: By the way, should the converse also be done; if actnum is 0, set poro and ntg to 0?

No

**Comment by joakim-hove** [comment]
Hmmm - when thinking more about it I guess this should be a post processor on the `ACTNUM`; we will handle it.

**Comment by totto82** [comment]
> Hmmm - when thinking more about it I guess this should be a post processor on the ACTNUM; we will handle it.

Thanks. 

>Well - as you correctly indicate this should be fixed in the parser; so why do you do it in opm-core? We should strive harder to fix the problems properly - and avoid band-aid solutions.

Agree, that's the reason for starting this discussion instead instead of providing the band-aid solution.

**Comment by joakim-hove** [comment]
OK @totto82: take a look at: https://github.com/OPM/opm-parser/pull/808

**Comment by totto82** [comment]
Thanks #808 did the trick.
