### ISSUE TITLE
Allow missing include file

### ISSUE THREAD

**Issue by magnesj** [OPM/opm-parser#826]
It must be possible to parse a file referencing another file which is missing without getting an exception. 

https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/Parser/tests/ParserIncludeTests.cpp#L73

**Comment by jokva** [comment]
Why must this be possible?

**Comment by alfbr** [comment]
Generally speaking allowing a missing include file will give highly unpredictable outcomes. Basically, we will have no knowledge on what keywords we may be skipping, and hence cannot trust anything the parser ends up relaying to a client, be it flow or resinsight. For this reason, we will probably want to stop flow at a missing include file logging a clear message to the user.

However, we are also expected to support the NOSIM option, which means that flow should allow for parsing through the whole deck and reporting all issues discovered. In this mode, we may even want flow to continue parsing after a missing include.

For usage in Resinsight, we already had this discussion last summer on the mailing list. Short answer is that Parsemode was created as an outcome of this discussion. It's intent is specifically to allow clients like Resinsight to determine themselves what errors in the input-deck to bypass.

Hence, in this case I would say the natural solution is that a parsemode (or is it parsecontext currently?) is added for missing includes. I guess the most effective solution is that we take the task on the parser side. Then again, Magne and Jacob may need to get familiar with the parsemode mechanism sooner or later anyway. Before we embark on that, Magne, are you really sure you want what you are asking for here? Remember, the missing include file could contain anything.

**Comment by jokva** [comment]
If it's something we want to relax via parse mode then the parser is surely the place.

**Comment by joakim-hove** [comment]
> It must be possible to parse a file referencing another file which is missing without getting an exception.

No - that is not something we *must* support, a missing include file is a quite severe user error and the moment we accept that error we embark on a potentially dangerous journey. It is not like people say: "Come on you nasty compiler  - a header here or a header there - don't be such a wimp"[1].

I agree that the `ParseMode` functionality in the Parser should be the place to implement support for this behavior - it should even be quite simple. The reason I do not embark on the task right away is:

1. For the other cases handled by the ParseMode we have a reasonably clear *make-the-best-out-of-it* recovery path - which we are reasonably confident will produce the result the user was after. If an include file is ignored all bets are more or less off.

2. The `Deck` produced by the `Parser::parseFile( )` is of course an important step, but the main product from the parser is the `EclipseState` object. If we we open up for ignoring missing include files I fear we will just move the exception from the `Deck` construction to the `EclipseState`, or at the very least risk silently creating an invalid `EclipseState`. The `EclipseState` object is created ~atomically at construction time - and I **really really** think we should avoid a situation where we must query the `EclipseState` instance about the internal state - i.e.

```C++
// No no - not like this:
if (eclState.hasGrid())
    grid = eclState.getInputGrid();
else
    std::cout << "Ehhh - I don't have a grid - what to do?" << std::endl;
```

**Validated deck**
In my opinion what we are missing is a way to validate a deck. If we had a method to guarantee that: "Yes - this deck has all the keywords required to make a valid `EclipseState`" we would have much more control. There was a suggestion for such validation here: https://github.com/OPM/opm-parser/issues/795; another alternative could be to create a `Validator` class which would spin through a deck and check for required keywords - with dependencies, then it would also be natural to implement different validators for different applications:

```C++
FlowValidator validator;

if (!validator.checkDeck(deck)) {
    std::cerr << "Sorry - could not create EclipseState from this deck";
    exit(1);
}
  
EclipseState state(deck);
flowMain.run( state );
```

```C++
RIValidator validator; // Not as strict as the FlowValidator
...
```
Alternatively the `EclipseDeck` of https://github.com/OPM/opm-parser/issues/795 could be implemented with a pluggable validator.

So for the way forward my wish is:

1. The deck in question is "fixed" - either by getting hold of the missing file or by just commenting out out the offending `INCLUDE` statement.

2. We implement a method to validate Decks - so that we can guarantee that a concrete `Deck`instance can be used as foundation for `EclipseState` construction. This will take some time.

3. We keep this issue open - and when we are happy with 2) we implement the `PARSER_IGNORE_MISSING_INCLDUE` error mode in `ParseContext`; in isolation that should be a 30 min effort. 

But if we embark on this journey everyone must accept that the return value from `validator.checkDeck( deck )` can be `false` - and that will be the ultimate end of the road.


[1]: Of course I know the parser is not a compiler, but the comparison is not that far fetched - for at least two reasons:

1. The Eclipse data file format can be meaningfully compared with an interpreted programming language.
2. The parser like a compiler works in several stages, where the results of one stage is passed on to the next stage. In the case of the parser there are two stages producing first the `Deck` and then the `EclipseState`respectively.

Both of these arguments point to the fact that the final state presented to application scope is the result of all preceding statements, and that it is difficult to isolate the consequences of an error to one lexical unit.

**Comment by joakim-hove** [comment]
> This means that we do not care about the state of the DATA file, 

Well - we care!

But seriously we need to know how you envisage to use the parser in Resinsight. My arguments hinge on the assumption that you will use the full `EclipseState` object. That is certainly the "best quality data in town" - but it is also the most demanding when it comes to consistency and so on.

**Comment by hhtesting** [comment]
During post-processing work, missing input files can be the case when files are gzip'ed or deleted to save disk space, typically when multiple realizations are created in automatic workflows. Still, it would be more user friendly (efficient) to have ResInsight reading what is available in the DATA deck, but then make a warning and list the Include files not found.

**Comment by magnesj** [comment]
In ResInsight, there are two workflows accessing data from the input files

1. Import of input case, including grid and properties
Currently implemented using ERT directly
**Plan: Replace all functionality with opm-parser**

2. Import of faults for binary cases
When an output case is imported,  the fault names are read from `*.DATA` file. This is the only information read from the input files in this workflow.
**Plan: Replace reading of FAULTS using opm-parser**

For item 2. we suggest possibility for reading faults even if some input files are missing.

**Comment by joakim-hove** [comment]
> In ResInsight, there are two workflows accessing data from the input files [....]

OK - thank you for the explanation. Case 1) certainly requires a validated Deck, for case 2) I see that it could be some merit to being able to proceed with missing include files. We will implement the required support in `ParseContext` - but not before we have some support for Deck validation. That will take some time.

**Comment by alfbr** [comment]
I don't think we need a deck validation for this. It is probably sufficient to have additional parsecontext for failed Eclipsestate creation as fault names can be parsed straight from the deck.

**Comment by magnesj** [comment]
Tested https://github.com/OPM/opm-parser/commit/768a1e922759cff938d03924a04f59f235594150, and the fix works as expected.

Thanks!
