### ISSUE TITLE
Production controls added for phases that don't exist

### ISSUE THREAD

**Issue by ANerd** [OPM/opm-parser#829]
I am trying to run a two-phase problem (oil-water) in flow (master branch), but I get the following exception:

> [<...>/opm-core/opm/core/wells/WellsManager.cpp:599] Gas phase not active and GRAT control specified.

After some investigation I found the code where the GRAT-control is added, which is [here](https://github.com/OPM/opm-parser/blob/c46b1cb9369d328056bd6a9e45513cbca5420650/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp#L52) (the case uses WCONHIST):

``` cpp
for (auto const& modeKey : {"ORAT", "WRAT", "GRAT", "LRAT", "RESV", "GRUP"}) {
    auto cmode = WellProducer::ControlModeFromString( modeKey );
    p.addProductionControl( cmode );
}
```

This code seems to add all production controls without checking what phases are active. Just removing "GRAT" from this list fixes the problem (but that will obviously break something for three-phase runs).

The code for prediction mode ([here](https://github.com/OPM/opm-parser/blob/c46b1cb9369d328056bd6a9e45513cbca5420650/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp#L95)) seems to be doing something smarter

``` cpp
for (auto const& modeKey : {"ORAT", "WRAT", "GRAT", "LRAT","RESV", "BHP" , "THP"}) {
    if (!record.getItem(modeKey).defaultApplied(0)) {
        auto cmode = WellProducer::ControlModeFromString( modeKey );
        p.addProductionControl( cmode );
    }
}
```

I imagine the issue can be fixed by something like [this](https://gist.github.com/ANerd/adc224e99890ebff75cbed4959139d82), but I don't know enough about the code to know if this breaks something else.

**Comment by joakim-hove** [comment]
Thank you for a very good problem report. If I stretch my brain to the breaking limit I come up with the following situation report:

1. When running under `WCONHIST` the rates `GRAT`, `WRAT` and `ORAT` double up as both possible target rates, and a way to input the historical rates to the simulator - for subsequent output as `xxxH` keywords in the summary file.

2. Since these values are historically allocated values they are "always" present with a value - the default value of 0.0 is also OK. 

So; I guess your fix would do it - but in my opinion a better fix would consult the phases available and set the controls accordingly:
```C++
if (hasPhase( Phase::OIL ))
    p.addProductionControl( WellProducer::ORAT );

if (hasPhase( Phase::GAS ))
   p.addProductionControl( WellProducer::GRAT );

if (hasPhase( Phase::WATER ))
   p.addProductionControl( WellProducer::WRAT );

for (auto const& modeKey : {"LRAT", "RESV", "GRUP"}) {
    auto cmode = WellProducer::ControlModeFromString( modeKey );
    p.addProductionControl( cmode );
}
```

Unfortunately the `Schedule::hasPhase( )` method currently only exists in this comment :disappointed: The `TableManager` is the current canonical owner of this information - feel free to submit a PR!

I am going offline for a couple of days now; so there will be immediate progress on this - but for now I assume your fix should get you going at least.

**Comment by jokva** [comment]
https://github.com/OPM/opm-parser/pull/953
