### ISSUE TITLE
Pressure controlled injector and 'NO' crossflow

### ISSUE THREAD

**Issue by osae** [OPM/opm-parser#831]
Disallowing crossflow (WELSPECS, item10:  'NO') seems to cause the well to remain shut forever ...

**Comment by atgeirr** [comment]
Is this where the WTEST keyword comes into play (which we don't support at all I think).

**Comment by osae** [comment]
Eclipse works perfectly for this case without kw WTEST. 
Running a very simple case, the problem is not that the well is shut down due to crossflow actually occurring, but that the well is kept shut from day zero as a default choice from Schedule.

**Comment by alfbr** [comment]
@osae , any chance you can provide a proposed solution with in a pull request?

**Comment by OPMUSER** [comment]
No, the cross-flow No option stops cross flow in the wellbore so that 
all the fluid goes up the wellbore. If Yes is used then some fluids may 
enter other layers that are depleted instead of continuing up the 
wellbore. These zones/layers are known as "thief zones". In both cases 
the well status is not changed (that is Open or Shut), it is just 
whether or not fluid is allowed to re-enter the reservoir. It is 
possible to shut-in the well at the surface (setting the rate to zero) 
but still have the completions open (with or without cross-flow).

WTEST is for something else, when the well has been shut-in due to a 
constraint (well will not flow due THP limit for example), then engineer 
may reset those constraints and ask Eclipse to re-test the well to see 
if it will flow under the new set of conditions. The keyword enables 
automatic testing instead of inserting the appropriate keywords to open 
the well at every constraint change.

ThunderBird Signature File

Regards, David Baxendale Email: David.Baxendale@gmail.com

------------------------------------------------------------------------

**Comment by joakim-hove** [comment]
> Running a very simple case, the problem is not that the well is shut down due to crossflow actually occurring, but that the well is kept shut from day zero as a default choice from Schedule.

Just to check my understanding:

1. The well starts out as `SHUT`.
2. When simulating with `flow` the well remains shut for the entire simulation.
3. When simulating with Eclipse the well opens at some point in time. What triggers this opening?

Sounds like it would be valuable to have a look at the deck in question.

**Comment by OPMUSER** [comment]
Send me the deck and I'll have a look - if you are unsure of the what it is
suppose to do.

On Fri, Jun 10, 2016 at 2:03 AM, Joakim Hove <notifications@github.com>
wrote:

> Running a very simple case, the problem is not that the well is shut down
> due to crossflow actually occurring, but that the well is kept shut from
> day zero as a default choice from Schedule.
>
> Just to check my understanding:
>
>    1. The well starts out as SHUT.
>    2. When simulating with flow the well remains shut for the entire
>    simulation.
>    3. When simulating with Eclipse the well opens at some point in time.
>    What triggers this opening?
>
> Sounds like it would be valuable to have a look at the deck in question.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OPM/opm-parser/issues/831#issuecomment-224977777>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARIIDy3lziboMOsDuE9e2b6_DDUh-j4wks5qKFV_gaJpZM4Iw1Dq>
> .
>



-- 
Regards

David Baxendale
david.baxendale@gmail.com

**Comment by osae** [comment]
1) From deck it is assumed to be open from day zero.
2) Yes
3) Open from day zero, as expected from input.

WELSPECS
'I' 'G'  1 1 50. 'WATER' 0.0 'STD' 'SHUT' 'YES' /  Runs fine in opm ...

WELSPECS
'I' 'G'  1 1 50. 'WATER' 0.0 'STD' 'SHUT' 'NO' / Fine with ECL.  Never gets a chance in opm ...

WCONINJE
'I' 'WATER' 'OPEN' 'BHP' 2* 151.0 /

Have set up a producer in a similar way.  
Seems ok (i.e. open) from day zero in both ECL and opm.  
Must be some difference in the handling of WCONINJE versus WCONPROD ...

**Comment by joakim-hove** [comment]
>1) From deck it is assumed to be open from day zero.
2) Yes
3) Open from day zero, as expected from input.
[....]

OK - this is still somewhat unclear to me; but now my summary is:

**1:** The well is created with the `WELSPECS` record:
```txt
WELSPECS
'I' 'G' 1 1 50. 'WATER' 0.0 'STD' 'SHUT' 'NO' /
```
i.e. initially `SHUT` and with banned crossflow.

**2:** The well is later opened with the `WCONINJE` record:
```txt
WCONINJE
 'I' 'WATER' 'OPEN' 'BHP' 2* 151.0 /
```

**Bug:** When simulating with `flow` the `OPEN` statement in `WCONINJE` never applies, and the well remains shut.

**Comment by osae** [comment]
Precisely. (Seems to me that there is a test in Schedule::handleWCONINJE that a pressure controlled injector never will pass due to having a trivial initial rate).

**Comment by GitPaean** [comment]
I think this issue is possibly solved by https://github.com/OPM/opm-parser/pull/1209 , at least for injectors.

**Comment by GitPaean** [comment]
I believe this is fixed, feel free to reopen it otherwise.
