### ISSUE TITLE
Problems with localization

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-parser#973]
there seem to be some problems in the interactions of boost and locales that sometimes break the build or cause the unit tests to fail. This is particularly annoying because it seems to happen frequently: it seems like the issue can be triggered using a freshly installed Ubuntu that was set up with a non-default locale.

Further reading: #971

**Comment by jokva** [comment]
We've now merged #1002, but this issue is largely a wontfix. Here's why (for future reference):

* The problem arises because boost pre-1.57 calls `std::locale("")` which yields the user preferred locale. On linux this seems to be governed by LC_ALL and other LC_* and the LANG environment variables.
* There's no good way to override this without going platform specific, e.g. check if `std::locale("")` throws and then override user environment to a fallback encoding (C) if unix or whatever you need to do on windows. This is in my opinion a *clear* violation of what a library is supposed to do if it's permanent, and such a hassle if it's on a per-function call. It's also a work-around for the users fundamentally broken environment, and if we're to go lengths to handle all permutations of broken user envs we're in for a ride. Flow and other applications are obviously free to make this choice, which is a nice user friendly feature, but it's not for opm-parser to do.
* The issue seems to be way less of a problem with boost >= 1.57, so whenever we either require a newer boost this probably goes away.

**Comment by atgeirr** [comment]
We cannot handle all permutations of broken environments, but if important cases such as a near-default setup of Ubuntu breaks we should be prepared to handle it gracefully. I do not quite understand what is "broken" with the user environment in these cases though.

Is the boost thing a bug in some sense? If so, we should require newer boost to avoid it if that solves everything.

**Comment by jokva** [comment]
> I do not quite understand what is "broken" with the user environment in these cases though.
Usually language being set to some locale that isn't generated. Using a richer installer, installing US or forcing C locale always solves this problem.

> Is the boost thing a bug in some sense? If so, we should require newer boost to avoid it if that solves everything.

Yes, but RH7 ships with 1.53.
